### ISSUE TITLE
Any Upcoming new models?

### ISSUE THREAD

**Issue by 2994dd42d75b0** [98mxr/GMFSS_Fortuna#10]
Union is great but its slow will there be any new version with better processing speed?

**Comment by 98mxr** [comment]
I've tried some more efficient programs, but they don't bring similar quality to union, and GMFSS isn't going to get any faster for some foreseeable time.

**Comment by 2994dd42d75b0** [comment]
Any way to use 2 GPUS Can you add multi GPU support ?

**Comment by 98mxr** [comment]
I'm sorry to say I'm not good at this kind of software engineering, so I'll have to hope for others who are passionate about this project.

**Comment by 2994dd42d75b0** [comment]
Okay Thanks.
