### ISSUE TITLE
'python3' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Ihateyoudattebayo** [98mxr/GMFSS_Fortuna#2]
I tried running it, but I got this error, I have python installed through path

**Comment by 98mxr** [comment]
Maybe try using `python xxxx.py` directly

**Comment by Ihateyoudattebayo** [comment]
> Maybe try using `python xxxx.py` directly
I get this now.
SyntaxError: Non-UTF-8 code starting with '\xac' in file C:\Users\galax\GMFSS_Fortuna\mon.mp4 on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

**Comment by Ihateyoudattebayo** [comment]
> Maybe try using `python xxxx.py` directly

I get this now.
SyntaxError: Non-UTF-8 code starting with '\xac' in file C:\Users\galax\GMFSS_Fortuna\mon.mp4 on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details
