### ISSUE TITLE
NameError: name 'Model' is not defined

### ISSUE THREAD

**Issue by 65MDVK** [98mxr/GMFSS_Fortuna#4]
D:\GMFSS\GMFSS_Fortuna>python inference_video.py --video="D:\GMFSS\GMFSS_Fortuna\demo\1.mp4" --scale=1.0 --multi=2 --union 
Please download model from model list or Check if it is a union model
Traceback (most recent call last):
  File "D:\GMFSS\GMFSS_Fortuna\inference_video.py", line 102, in <module>
    model = Model()
NameError: name 'Model' is not defined

Tried setting the model path with --model="path",got the same error

Models were downloaded and unzipped,with the train_log being placed in the root directory. Not sure what I did wrong. Same result with base/union models.

**Comment by 98mxr** [comment]
I'm not sure about this, I'll try again myself.

**Comment by 2994dd42d75b0** [comment]
install "numpy<1.22"
