### ISSUE TITLE
When installing with ComfyUI I get 

### ISSUE THREAD

**Issue by Infinitusvoid** [98mxr/GMFSS_Fortuna#6]
Error occurred when executing GMFSS Fortuna VFI:

CuPy failed to load nvrtc64_112_0.dll: FileNotFoundError: Could not find module 'nvrtc64_112_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

and a lot more

**Comment by 98mxr** [comment]
Cupy requires a local installation of the CUDA runtime, not like pytorch.
